[www]
clear_env = no
catch_workers_output = yes

pm = dynamic
pm.max_children = 12
pm.start_servers = 3
pm.min_spare_servers = 2
pm.max_spare_servers = 6
pm.max_requests = 500

request_terminate_timeout = 120s

ping.path = /fpm-ping
pm.status_path = /fpm-status
